Repository prgrms-fe-devcourse/FES-5-Project3-TEAM-1, pull requests merged in 2025-08, with the labels that each got.

#2 Feature/default input 204
  src/assets/favicon.ico
  src/assets/logo.png
  src/shared/components/Input/assets/time.svg
  src/shared/components/Input/index.tsx
Labels: ui

#6 [feat] 디폴트 input 구현
  .gitignore
  src/assets/icon/clock-15.svg
  src/assets/icon/delete-15.svg
  src/assets/icon/eye-close-15.svg
  src/assets/icon/eye-open-15.svg
  src/pages/Home/index.tsx
  src/shared/components/Input/index.tsx
  src/shared/styles/_utilities.css
  src/shared/styles/global.css
Labels: feature

#15 Feature/default popup 9
  .husky/pre-push
  package.json
  src/RootLayout.tsx
  src/assets/icon/close-24.svg
  src/features/card/ui/DefaultCard.tsx
  src/pages/ModalTest/index.tsx
  src/pages/Showcase/index.tsx
  src/router/router.tsx
  src/shared/components/Button/index.tsx
  src/shared/components/Footer/index.tsx
  src/shared/components/Header/index.tsx
  src/shared/components/Input/BaseInput.tsx
  src/shared/components/Input/InputActionButton.tsx
  src/shared/components/Input/Password.tsx
  src/shared/components/Input/Row.tsx
  src/shared/components/Input/TimePicker.tsx
  src/shared/components/Input/index.ts
  src/shared/components/Modal/ConfirmModal.tsx
  src/shared/components/Modal/InputModal.tsx
  src/shared/components/Modal/ModalLayout.tsx
  src/shared/components/Modal/index.ts
  src/shared/components/Modal/inputModal/Password.tsx
  src/shared/components/Modal/inputModal/Text.tsx
  src/shared/components/Modal/inputModal/index.ts
  src/shared/components/Portal/Portal.tsx
  src/shared/components/Portal/index.ts
  src/shared/styles/_base.css
  src/shared/styles/_components.css
  src/shared/styles/_theme.css
  src/shared/styles/_utilities.css
  src/shared/styles/global.css
  src/shared/types/supabase.ts
Labels: ui, feature

#33 Feature/toast implement 31
  src/assets/icon/error-16.svg
  src/assets/icon/info-16.svg
  src/assets/icon/success-16.svg
  src/features/emoji/components/EmojiButton.tsx
  src/features/emoji/components/EmojiItem.tsx
  src/features/emoji/components/EmojiList.tsx
  src/main.tsx
  src/pages/ModalTest/index.tsx
  src/shared/styles/_theme.css
  src/shared/utils/toastUtils.tsx
Labels: ui, feature

#41 Feature/enter page 34
  src/RootLayout.tsx
  src/features/thread/create-thread/CreateThread.tsx
  src/pages/Thread/components/PasswordModal.tsx
  src/pages/Thread/hooks/useThread.ts
  src/pages/Thread/index.tsx
  src/router/router.tsx
  src/shared/api/thread.ts
  src/shared/components/modals/InputModal.tsx
  src/shared/components/modals/ModalLayout.tsx
  src/shared/components/portals/Portal.tsx
  src/shared/utils/sessionStorage.ts
Labels: ui, feature

#49 [feature] Login 기능 추가 구현
  src/features/login/hooks/GithubLogin.ts
  src/features/login/hooks/GoogleLogin.ts
  src/features/login/hooks/useGithubLogin.ts
  src/features/login/hooks/useGoogleLogin.ts
  src/features/login/hooks/useHandleAdminPage.ts
  src/features/login/hooks/useLogout.ts
  src/features/login/ui/GithubLoginButton.tsx
  src/features/login/ui/GoogleLoginButton.tsx
  src/features/login/ui/LoginModal.tsx
  src/features/login/ui/LogoutButton.tsx
  src/features/login/ui/WelcomeModal.tsx
  src/main.tsx
  src/pages/Home/index.tsx
  src/pages/login-test/LoginTest.tsx
  src/router/router.tsx
  src/shared/types/supabase.ts
  src/shared/utils/AuthProvider.tsx
  src/shared/utils/LoginAuth.tsx
  src/shared/utils/ModalProvider.tsx
Labels: feature

#50 Feature/default feeds 46
  src/pages/Showcase/index.tsx
  src/pages/Thread/components/CreateFeed.tsx
  src/pages/Thread/components/FeedList.tsx
  src/pages/Thread/hooks/useFeed.ts
  src/pages/Thread/hooks/useFeedUpload.ts
  src/pages/Thread/hooks/useThreadAuthentication.ts
  src/pages/Thread/index.tsx
  src/shared/api/feed.ts
  src/shared/api/thread.ts
  src/shared/components/feed-Input/FeedInput.tsx
  src/shared/components/feed-Input/FeedOptions.tsx
  src/shared/types/feed.ts
  src/shared/types/supabase.ts
Labels: feature

#52 [Feature] Login 요구사항 구현
  src/features/login/hooks/useLogout.ts
  src/features/login/ui/WelcomeModal.tsx
  src/shared/components/header/Header.tsx
  src/shared/utils/AuthProvider.tsx
  src/shared/utils/ModalProvider.tsx
Labels: feature

#57 Features/drawing 39
  package-lock.json
  package.json
  src/assets/icon/back-24.svg
  src/assets/icon/eraser-24.svg
  src/assets/icon/fill-24.svg
  src/assets/icon/pen-24.svg
  src/assets/icon/refresh-24.svg
  src/assets/icon/square-24.svg
  src/features/drawing/types/drawing.ts
  src/features/drawing/ui/Canvas.tsx
  src/features/drawing/ui/ColorPalette.tsx
  src/features/drawing/ui/DrawingForm.tsx
  src/features/drawing/ui/ToolBar.tsx
  src/shared/components/feed-Input/FeedInput.tsx
  src/shared/components/header/Header.tsx
Labels: feature

#70 feat : 방 정보 수정하기 모달 기능 구현
  src/RootLayout.tsx
  src/features/thread/create-thread/CreateThread.tsx
  src/pages/login-test/LoginTest.tsx
  src/shared/api/thread.ts
  src/shared/utils/ModalProvider.tsx
Labels: feature

#72 [feat] 이모지 실시간 업데이트 기능 구현
  src/features/emoji/hook/useEmoji.ts
  src/features/emoji/hook/useEmojiSubscription.ts
  src/shared/api/emoji.ts
  src/shared/api/feed.ts
Labels: feature

#90 Feature/emoji debounce 84
  src/features/emoji/hook/useEmoji.ts
  src/pages/Thread/components/VirtualFeedItem.tsx
  src/shared/hook/useDebounce.ts
Labels: feature

#93 Bug/comment bug 91
  src/features/comment/component/CommentInput.tsx
  src/features/comment/component/CommentList.tsx
  src/features/comment/component/CommentSection.tsx
  src/features/comment/hook/useComment.ts
  src/features/emoji/components/EmojiButton.tsx
  src/features/emoji/components/EmojiGrid.tsx
  src/features/emoji/components/EmojiItem.tsx
  src/features/emoji/ui/EmojiPicker.tsx
  src/pages/Thread/components/FeedCard.tsx
  src/pages/Thread/components/VirtualFeedItem.tsx
Labels: ui, feature

#99 Bug/bug fix 6
  src/RootLayout.tsx
  src/features/comment/component/CommentInput.tsx
  src/features/comment/component/CommentList.tsx
  src/features/comment/component/CommentModal.tsx
  src/features/comment/hook/useComment.ts
  src/features/easter-egg/components/Beom.tsx
  src/features/easter-egg/components/EasterEggSection.tsx
  src/features/easter-egg/hook/useCreateTriggerEventChannel.ts
  src/features/easter-egg/utils/store.ts
  src/features/easter-egg/utils/trigger.ts
  src/features/easter-egg/utils/triggerRegistry.ts
  src/features/emoji/components/EmojiGrid.tsx
  src/features/emoji/hook/useEmoji.ts
  src/features/thread/utils/store.ts
  src/features/thread/utils/type.ts
  src/main.tsx
  src/pages/Thread/components/CreateFeed.tsx
  src/pages/Thread/components/FeedCard.tsx
  src/pages/Thread/components/VirtualFeedItem.tsx
  src/pages/Thread/components/VirtualFeedList.tsx
  src/pages/Thread/components/feed/EmptyFeed.tsx
  src/pages/Thread/components/feed/ImageFeed.tsx
  src/pages/Thread/hooks/useFeed.ts
  src/pages/Thread/hooks/useFeedUpload.ts
  src/pages/Thread/hooks/useFeedVirtualizer.ts
  src/pages/Thread/hooks/useInfiniteScroll.ts
  src/pages/Thread/hooks/useThreadAuthentication.ts
  src/pages/Thread/index.tsx
  src/pages/Thread/utils/sortFeeds.ts
  src/pages/Thread/utils/store.ts
  src/router/index.tsx
  src/router/router.tsx
  src/router/routes.ts
  src/router/type.ts
  src/shared/api/comment.ts
  src/shared/api/easter-egg.ts
  src/shared/api/emoji.ts
  src/shared/components/card-Layout/CardLayout.tsx
  src/shared/components/feed-Input/FeedInput.tsx
  src/shared/components/feed-card/Card.tsx
  src/shared/components/feed-card/CardFooter.tsx
  src/shared/components/feed-card/CardHeader.tsx
  src/shared/components/header/Header.tsx
  src/shared/components/modals/PasswordModal.tsx
  src/shared/components/selector/SortSelector.tsx
  src/shared/hook/useThrottle.ts
  src/shared/types/supabase.ts
Labels: ui, feature, delete, style

#104 Feature/confetti easter egg
  package-lock.json
  package.json
  src/features/easter-egg/components/Confetti.tsx
  src/features/easter-egg/utils/trigger.ts
  src/features/easter-egg/utils/triggerRegistry.ts
Labels: feature

#105 [feat] 정렬 selector UI -> 정렬 tab 형식으로 변경
  src/pages/Thread/index.tsx
  src/shared/components/selector/SortSelector.tsx
  src/shared/components/tab/SortTab.tsx
Labels: style
